version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "s3-copy-file-nodejs"
resolve_s3 = true
s3_prefix = "s3-copy-file-nodejs"
region = "eu-north-1"
capabilities = "CAPABILITY_IAM"
