AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
  S3CopyFile:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: s3_copy_file_nodejs
      ContentUri: .
      CompatibleRuntimes:
        - nodejs18.x
        - nodejs20.x
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: makefile
  TestBucket:
    Type: AWS::S3::Bucket
  TestLambda:
    Type: AWS::Serverless::Function
    Properties:
      Handler: index.handler
      Runtime: nodejs20.x
      CodeUri: ./testing-lambda-extension
      Timeout: 10
      Layers:
        - !Ref S3CopyFile
      Environment:
        Variables:
          S3_BUCKET: !Ref TestBucket
          S3_KEY: test.txt
      Policies:
        - S3ReadPolicy:
            BucketName: !Ref TestBucket
  